name: Issue Trigger and Output
on: 
  issues:
    types:
      - opened
      - closed
      - edited
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
    - name: Output Github Info
      run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
